language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-29.0.2
    # The SDK version used to compile your project
    - android-29

    # Support library
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - ./gradlew build

